name: Build and Push Docker Image

on:
  push:
    branches:
      - setup 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with your Docker Hub password

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: allanconstanza/my-nodejs-app:latest  # Replace with your Docker Hub username and desired image name

    - name: Verify application functionality
      uses: liatrio/apprentice-action@v1  # Optional: Verifies functionality using Liatrio's action
